import = [
  "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]

[window]
#dimensions = {columns = 120, lines = 40}
opacity = 0.9 
blur = true
padding.x = 5
padding.y = 5
startup_mode = "Maximized"
decorations = "None"
option_as_alt = "Both"
#decorations_theme_variant = "Light" # "Dark"

[font]

normal.family = "Hasklug Nerd Font Mono"
bold.family = "Hasklug Nerd Font Mono"
italic.family = "Hasklug Nerd Font Mono"
bold_italic.family = "Hasklug Nerd Font Mono"

size = 18.0

[shell]
program = "/bin/bash"
args = [ "--login" ]
